<a href="https://colab.research.google.com/github/Chinedu-analysis/Chinedu-analysis/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [5]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [6]:
%%sql

Select *
From information_schema.columns
WHERE table_name = 'customer'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,customer,startdt,3,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,customer,enddt,4,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,customer,birthday,18,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,customer,age,19,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,customer,latitude,23,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,customer,longitude,24,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,customer,middleinitial,9,None,YES,character varying,5.00,20.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,customer,surname,10,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,customer,streetaddress,11,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,customer,city,12,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,customer,state,13,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,customer,statefull,14,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,customer,zipcode,15,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,customer,country,16,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,customer,countryfull,17,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,contoso_100k,public,customer,company,21,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,contoso_100k,public,customer,vehicle,22,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,contoso_100k,public,customer,occupation,20,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,contoso_100k,public,customer,continent,5,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,contoso_100k,public,customer,gender,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,contoso_100k,public,customer,title,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,contoso_100k,public,customer,givenname,8,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [7]:
%%sql

Select *
From date
Limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2
5,2015-01-06,20150106,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Tuesday,Tue,3,1,3
6,2015-01-07,20150107,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Wednesday,Wed,4,1,4
7,2015-01-08,20150108,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,1,5
8,2015-01-09,20150109,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,6
9,2015-01-10,20150110,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,6

In [8]:
%%sql

Select
  quantity,
  netprice,
  quantity * netprice as net_revenue
From sales
Limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   quantity  netprice  net_revenue
0         1     98.97        98.97
1         1    659.78       659.78
2         2     54.38       108.75
3         4    286.69      1146.75
4         7    135.75       950.25
5         3    434.30      1302.91
6         1     58.73        58.73
7         3     74.99       224.98
8         2    113.57       227.15
9         1    499.45       499.45

In [9]:
%%sql

Select
  *,
  quantity * netprice * exchangerate as net_revenue
From sales
Limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate,net_revenue
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64,63.49
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64,423.28
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00,108.75
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00,1146.75
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00,950.25
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00,1302.91
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00,58.73
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00,224.98
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16,263.11
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16,578.52

In [10]:
%%sql

Select
  orderdate,
  quantity * netprice * exchangerate as net_revenue
From sales
Where
  Cast(orderdate as date) >= '2020-01-01'
Limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2020-01-01        99.47
1  2020-01-01       139.97
2  2020-01-01       669.39
3  2020-01-01      4090.60
4  2020-01-01       237.15
5  2020-01-01      1507.16
6  2020-01-01       189.35
7  2020-01-01       539.90
8  2020-01-01      5590.00
9  2020-01-01      3580.00

In [11]:
%%sql

Select
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate as net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p productname,
  p.categoryname,
  p.subcategoryname
From sales s
Left join customer c on s.customerkey = c.customerkey
Left join product p on s.productkey = p.productkey
Where
  Cast(orderdate as date) >= '2020-01-01'
Limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,"(1810,702104,""MGS Bicycle Card Games2009 E166""...",Games and Toys,Download Games
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,"(1809,702103,""MGS Bicycle Board Games2009 E165...",Games and Toys,Download Games
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,"(698,306057,""Proseware Wireless Photo All-in-O...",Computers,"Printers, Scanners & Fax"
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,"(364,301027,""Adventure Works Laptop12 M1200 Bl...",Computers,Laptops
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,"(1288,406042,""Contoso Genuine Leather Grip Bel...",Cameras and camcorders,Cameras & Camcorders Accessories
5,2020-01-01,1507.16,Jason,Smith,United States,North America,2061,"(2061,803079,""Contoso Microwave 1.5CuFt X0110 ...",Home Appliances,Microwaves
6,2020-01-01,189.35,Jason,Smith,United States,North America,1717,"(1717,702011,""MGS Flight Simulator X M250"",""Ta...",Games and Toys,Download Games
7,2020-01-01,539.90,Jason,Smith,United States,North America,435,"(435,303020,""Adventure Works Desktop PC1.60 ED...",Computers,Desktops
8,2020-01-01,5590.00,James,Frye,United States,North America,451,"(451,303036,""WWI Desktop PC2.30 M2300 Silver"",...",Computers,Desktops
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,535,"(535,304075,""WWI LCD19W M100 White"",""Wide Worl...",Computers,Monitors

In [12]:
%%sql

Select
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate as net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p productname,
  p.categoryname,
  p.subcategoryname,
  CASE WHEN s.quantity * s.netprice * s.exchangerate > 1000 Then 'High' Else 'Low' End As net_revenue_category
From sales s
Left join customer c on s.customerkey = c.customerkey
Left join product p on s.productkey = p.productkey
Where
  Cast(orderdate as date) >= '2020-01-01'
Limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,net_revenue_category
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,"(1810,702104,""MGS Bicycle Card Games2009 E166""...",Games and Toys,Download Games,Low
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,"(1809,702103,""MGS Bicycle Board Games2009 E165...",Games and Toys,Download Games,Low
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,"(698,306057,""Proseware Wireless Photo All-in-O...",Computers,"Printers, Scanners & Fax",Low
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,"(364,301027,""Adventure Works Laptop12 M1200 Bl...",Computers,Laptops,High
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,"(1288,406042,""Contoso Genuine Leather Grip Bel...",Cameras and camcorders,Cameras & Camcorders Accessories,Low
5,2020-01-01,1507.16,Jason,Smith,United States,North America,2061,"(2061,803079,""Contoso Microwave 1.5CuFt X0110 ...",Home Appliances,Microwaves,High
6,2020-01-01,189.35,Jason,Smith,United States,North America,1717,"(1717,702011,""MGS Flight Simulator X M250"",""Ta...",Games and Toys,Download Games,Low
7,2020-01-01,539.90,Jason,Smith,United States,North America,435,"(435,303020,""Adventure Works Desktop PC1.60 ED...",Computers,Desktops,Low
8,2020-01-01,5590.00,James,Frye,United States,North America,451,"(451,303036,""WWI Desktop PC2.30 M2300 Silver"",...",Computers,Desktops,High
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,535,"(535,304075,""WWI LCD19W M100 White"",""Wide Worl...",Computers,Monitors,High

In [13]:
%%sql

Select
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate as net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p productname,
  p.categoryname,
  p.subcategoryname,
  CASE WHEN s.quantity * s.netprice * s.exchangerate > 1000 Then 'High' Else 'Low' End As net_revenue_category
From sales s
Left join customer c on s.customerkey = c.customerkey
Left join product p on s.productkey = p.productkey
Where
  Cast(orderdate as date) >= '2020-01-01'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,net_revenue_category
0,2020-02-27,664.66,Jonas,Propst,Germany,Europe,459,"(459,303044,""WWI Desktop PC1.80 E1801 White"",""...",Computers,Desktops,Low
1,2020-02-28,782.87,Michael,Rodriguez,United States,North America,429,"(429,303014,""Adventure Works Desktop PC2.30 MD...",Computers,Desktops,Low
2,2020-01-01,56.02,Swen,Saenger,Germany,Europe,1584,"(1584,602014,""SV DVD 38 DVD Storage Binder E25...","Music, Movies and Audio Books",Movie DVD,Low
3,2020-01-01,192.11,Swen,Saenger,Germany,Europe,1925,"(1925,802029,""Fabrikam Refrigerator 3.2CuFt E1...",Home Appliances,Refrigerators,Low
4,2020-01-01,174.65,Jan,Muller,Germany,Europe,562,"(562,305024,""Proseware Screen 80in E1010 White...",Computers,Projectors & Screens,Low
...,...,...,...,...,...,...,...,...,...,...,...
124446,2024-03-13,79.92,Patricia,Sanchez,United States,North America,2496,"(2496,505009,""Headphone Adapter for Contoso Ph...",Cell phones,Cell phones Accessories,Low
124447,2024-03-13,138.00,Patricia,Sanchez,United States,North America,500,"(500,304040,""Adventure Works CRT19 E10 Black"",...",Computers,Monitors,Low
124448,2024-03-13,152.80,Patricia,Sanchez,United States,North America,1600,"(1600,602030,""SV DVD External DVD Burner M200 ...","Music, Movies and Audio Books",Movie DVD,Low
124449,2024-03-13,109.99,Patricia,Sanchez,United States,North America,1603,"(1603,602033,""SV DVD 7-Inch Player Portable E2...","Music, Movies and Audio Books",Movie DVD,Low
124450,2024-03-13,2408.00,Patricia,Sanchez,United States,North America,1422,"(1422,503015,""The Phone Company Sharp Touch Sc...",Cell phones,Touch Screen Phones,High

In [14]:
%%sql

Select
  orderdate,
  Count(Distinct customerkey) total_customers
From
  Sales
Where
  Orderdate between '2023-01-01' And '2023-12-31'
Group by orderdate
Order by orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers
0    2023-01-01               12
1    2023-01-02               49
2    2023-01-03               64
3    2023-01-04               78
4    2023-01-05               87
..          ...              ...
359  2023-12-27               73
360  2023-12-28               75
361  2023-12-29               55
362  2023-12-30               91
363  2023-12-31                9

[364 rows x 2 columns]

In [15]:
%%sql

Select
 DISTINCT continent

From customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent
0      Australia
1  North America
2         Europe

In [16]:
%%sql

Select
  s.orderdate,
  Count(Distinct s.customerkey) total_customers
From
  Sales s
Left join customer c on s.customerkey = c.customerkey
Where
  s.orderdate between '2023-01-01' And '2023-12-31'
Group by s.orderdate
Order by s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers
0    2023-01-01               12
1    2023-01-02               49
2    2023-01-03               64
3    2023-01-04               78
4    2023-01-05               87
..          ...              ...
359  2023-12-27               73
360  2023-12-28               75
361  2023-12-29               55
362  2023-12-30               91
363  2023-12-31                9

[364 rows x 2 columns]

In [17]:
%%sql

Select
  s.orderdate,
  Count(Distinct Case when c.continent = 'Europe' then s.customerkey end) as eu_customers,
  Count(Distinct Case when c.continent = 'North America' then s.customerkey end) as na_customers,
  Count(Distinct Case when c.continent = 'Australia' then s.customerkey end) as au_customers
From
 Sales s
Left join customer c on s.customerkey = c.customerkey
Where
  s.orderdate between '2023-01-01' And '2023-12-31'
Group by s.orderdate
Order by s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  eu_customers  na_customers  au_customers
0    2023-01-01             6             5             1
1    2023-01-02            15            31             3
2    2023-01-03            17            44             3
3    2023-01-04            28            46             4
4    2023-01-05            22            57             8
..          ...           ...           ...           ...
359  2023-12-27            26            41             6
360  2023-12-28            24            44             7
361  2023-12-29            19            32             4
362  2023-12-30            25            50            16
363  2023-12-31             1             8             0

[364 rows x 4 columns]

In [18]:
%%sql

Select
  p.categoryname,
  Sum(s.quantity * s.netprice * s.exchangerate) as net_revenue
From
 Sales s
Left join product p on s.productkey = p.productkey
Group by p.categoryname
Order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  net_revenue
0                          Audio   5312898.10
1        Cameras and camcorders   18520360.66
2                    Cell phones  32624265.72
3                      Computers  90619022.05
4                 Games and Toys   1668574.13
5                Home Appliances  26607245.54
6  Music, Movies and Audio Books  10588311.00
7                   TV and Video  20466861.38

In [19]:
%%sql

Select
  p.categoryname,
  Sum(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate  else 0 end) as total_net_revenue_2022,
  Sum(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate  else 0 end) as total_net_revenue_2023
From
 Sales s
Left join product p on s.productkey = p.productkey
Group by p.categoryname
Order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,total_net_revenue_2022,total_net_revenue_2023
0,Audio,766938.21,688690.18
1,Cameras and camcorders,2382532.56,1983546.29
2,Cell phones,8119665.07,6002147.63
3,Computers,17862213.49,11650867.21
4,Games and Toys,316127.30,270374.96
5,Home Appliances,6612446.68,5919992.87
6,"Music, Movies and Audio Books",2989297.28,2180768.13
7,TV and Video,5815336.61,4412178.23

In [20]:
%%sql

Select
  p.categoryname,
  AVG(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate  else 0 end) as avg_net_revenue_2022,
  AVG(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate  else 0 end) as avg_net_revenue_2023
From
 Sales s
Left join product p on s.productkey = p.productkey
Group by p.categoryname
Order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  avg_net_revenue_2022  avg_net_revenue_2023
0                          Audio                 50.18                 45.06
1        Cameras and camcorders                 176.85                147.23
2                    Cell phones                194.66                143.89
3                      Computers                384.13                250.55
4                 Games and Toys                 15.60                 13.34
5                Home Appliances                390.05                349.20
6  Music, Movies and Audio Books                 93.37                 68.11
7                   TV and Video                425.35                322.72

In [21]:
%%sql

SELECT
    p.categoryname,
    AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS avg_net_revenue_2022,
    AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS avg_net_revenue_2023,
    MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE NULL END) AS min_net_revenue_2022,
    MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE NULL END) AS max_net_revenue_2022,
    MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE NULL END) AS min_net_revenue_2023,
    MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE NULL END) AS max_net_revenue_2023
FROM Sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_net_revenue_2022,avg_net_revenue_2023,min_net_revenue_2022,max_net_revenue_2022,min_net_revenue_2023,max_net_revenue_2023
0,Audio,50.18,45.06,9.31,3473.36,10.85,2730.87
1,Cameras and camcorders,176.85,147.23,6.74,15008.39,5.98,13572.00
2,Cell phones,194.66,143.89,2.53,7692.37,2.28,8912.22
3,Computers,384.13,250.55,0.83,38082.66,0.75,27611.60
4,Games and Toys,15.60,13.34,2.83,5202.01,3.49,3357.30
5,Home Appliances,390.05,349.20,4.04,31654.55,4.54,32915.59
6,"Music, Movies and Audio Books",93.37,68.11,7.29,5415.19,6.91,3804.91
7,TV and Video,425.35,322.72,41.30,30259.41,42.30,27503.12

In [22]:

%%sql

Select
  Percentile_cont(0.50) Within Group (Order By netprice) as median_price
  -- Avg(netprice) as avg_price
From sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_price
0        191.95

In [23]:
%%sql

SELECT
    p.categoryname,
    Percentile_cont(.5) within group (Order By (Case
      When s.orderdate between '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) End)) As y2022_median_sales,
    Percentile_cont(.5) within group (Order By (Case
      When s.orderdate between '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) End)) As y2023_median_sales
FROM Sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  y2022_median_sales  y2023_median_sales
0                          Audio              257.21              266.59
1        Cameras and camcorders               651.46              672.60
2                    Cell phones              418.60              375.88
3                      Computers              809.70              657.18
4                 Games and Toys               33.78               32.62
5                Home Appliances              791.00              825.25
6  Music, Movies and Audio Books              186.58              159.63
7                   TV and Video              730.46              790.79

In [24]:
#Categorize

# •"High Value" if quantity >= 2 and netprice >= 50
# •"Standard Order" otherwise

%%sql

Select
    orderdate,
    quantity,
    netprice,
    Case
       When quantity >= 2 and netprice >= 50 Then 'High Value Order'
       Else 'Standard Order'
       End as order_type

FROM Sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice        order_type
0  2015-01-01         1     98.97    Standard Order
1  2015-01-01         1    659.78    Standard Order
2  2015-01-01         2     54.38  High Value Order
3  2015-01-01         4    286.69  High Value Order
4  2015-01-01         7    135.75  High Value Order
5  2015-01-01         3    434.30  High Value Order
6  2015-01-01         1     58.73    Standard Order
7  2015-01-01         3     74.99  High Value Order
8  2015-01-01         2    113.57  High Value Order
9  2015-01-01         1    499.45    Standard Order

In [25]:
#Categorize

# •"Multiple High Value Items" if quantity >= 2 and netprice >= 100
# •"Single High Value Item" if netprice >= 100
# •"Multiple Standard Items" if quantity >= 2
# •"Single Standard Item" Otherwise

%%sql

Select
    orderdate,
    quantity,
    netprice,
    Case
       When quantity >= 2 and netprice >= 50 Then 'High Value Order'
       When netprice >= 100 Then 'Single High Value Item'
       When quantity >= 2 Then 'Multiple Standard Items'
       Else 'Single Standard Item'
       End as order_type

FROM Sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice              order_type
0  2015-01-01         1     98.97    Single Standard Item
1  2015-01-01         1    659.78  Single High Value Item
2  2015-01-01         2     54.38        High Value Order
3  2015-01-01         4    286.69        High Value Order
4  2015-01-01         7    135.75        High Value Order
5  2015-01-01         3    434.30        High Value Order
6  2015-01-01         1     58.73    Single Standard Item
7  2015-01-01         3     74.99        High Value Order
8  2015-01-01         2    113.57        High Value Order
9  2015-01-01         1    499.45  Single High Value Item

In [26]:
%%sql

Select
  Percentile_cont(0.5) Within Group (Order By (s.quantity * s.netprice * s.exchangerate)) AS median
From
  sales s
Where
  orderdate between '2022-01-01' AND '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  398.00

In [27]:
%%sql

With median_value AS (
Select
  Percentile_cont(0.5) Within Group (Order By (s.quantity * s.netprice * s.exchangerate)) AS median
From
  sales s
Where
  orderdate between '2022-01-01' AND '2023-12-31'
)

SELECT
    p.categoryname as category,
    SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
         And s.orderdate Between '2022-01-01' and '2022-12-31'
        THEN (s.quantity * s.netprice  * s.exchangerate) End) As low_net_revenue_2022,
    SUM(CASE WHEN  (s.quantity * s.netprice * s.exchangerate) >= mv.median
        And s.orderdate Between '2022-01-01' and '2022-12-31'
        THEN (s.quantity * s.netprice * s.exchangerate) End) As high_net_revenue_2022,
    SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
         And s.orderdate Between '2023-01-01' and '2023-12-31'
        THEN (s.quantity * s.netprice  * s.exchangerate) End) As low_net_revenue_2023,
    SUM(CASE WHEN  (s.quantity * s.netprice * s.exchangerate) >= mv.median
        And s.orderdate Between '2023-01-01' and '2023-12-31'
        THEN (s.quantity * s.netprice * s.exchangerate) End) As high_net_revenue_2023
FROM Sales s
LEFT JOIN product p ON s.productkey = p.productkey,
median_value mv
GROUP BY p.categoryname
ORDER BY p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2023,high_net_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87

In [28]:

%%sql

With percentiles As (
Select
  Percentile_cont(0.25) Within Group (Order By (quantity * netprice * exchangerate)) AS revenue_25th_percentile,
  Percentile_cont(0.75) Within Group (Order By (quantity * netprice * exchangerate)) AS revenue_75th_percentile
From
  sales
Where
  orderdate between '2022-01-01' AND '2023-12-31'
)

SELECT
    p.categoryname as category,
    CASE
        When (s.quantity * s.netprice * s.exchangerate) <= pctl.revenue_25th_percentile Then '1 - LOW'
        When (s.quantity * s.netprice * s.exchangerate) >= pctl.revenue_75th_percentile Then '3 - HIGH'
        Else '2 - MEDIUM'
    End As revenue_tier,
    SUM(s.quantity * s.netprice * s.exchangerate) As total_revenue
FROM Sales s
LEFT JOIN product p ON s.productkey = p.productkey,
percentiles pctl
GROUP BY p.categoryname, revenue_tier
ORDER BY p.categoryname, revenue_tier;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category revenue_tier  total_revenue
0                           Audio      1 - LOW      267217.01
1                           Audio   2 - MEDIUM     3832415.38
2                           Audio     3 - HIGH     1213265.71
3         Cameras and camcorders       1 - LOW       81032.92
4         Cameras and camcorders    2 - MEDIUM     3388546.10
5         Cameras and camcorders      3 - HIGH    15050781.63
6                     Cell phones      1 - LOW      410309.35
7                     Cell phones   2 - MEDIUM    10338963.22
8                     Cell phones     3 - HIGH    21874993.15
9                       Computers      1 - LOW      203207.06
10                      Computers   2 - MEDIUM    10808054.11
11                      Computers     3 - HIGH    79607760.89
12                 Games and Toys      1 - LOW      533443.13
13                 Games and Toys   2 - MEDIUM     1001381.91
14                 Games and Toys     3 - HIGH      133749.09
15                Home Appliances      1 - LOW      105045.60
16                Home Appliances   2 - MEDIUM     4118724.64
17                Home Appliances     3 - HIGH    22383475.30
18  Music, Movies and Audio Books      1 - LOW      642496.71
19  Music, Movies and Audio Books   2 - MEDIUM     6100817.99
20  Music, Movies and Audio Books     3 - HIGH     3844996.29
21                   TV and Video      1 - LOW       67221.76
22                   TV and Video   2 - MEDIUM     3766783.30
23                   TV and Video     3 - HIGH    16632856.33

In [29]:
%%sql

Select
  Current_Date

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2025-08-21

In [30]:
%%sql

Select
  Now()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

                               now
0 2025-08-21 14:56:04.008563+00:00

In [31]:
%%sql

SELECT
    s.orderdate,
    p.categoryname,
    SUM(quantity * netprice * exchangerate) as net_revenue
FROM Sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
    Extract(Year from orderdate) >= Extract( Year from current_date) - 5
GROUP BY s.orderdate, p.categoryname
Order BY s.orderdate, p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

11171 rows affected.

        orderdate                   categoryname  net_revenue
0      2020-01-01                          Audio      5490.14
1      2020-01-01        Cameras and camcorders      18880.06
2      2020-01-01                    Cell phones     22593.00
3      2020-01-01                      Computers     78554.54
4      2020-01-01                 Games and Toys      1476.43
...           ...                            ...          ...
11166  2024-04-20                      Computers     58353.68
11167  2024-04-20                 Games and Toys      1744.30
11168  2024-04-20                Home Appliances      1562.04
11169  2024-04-20  Music, Movies and Audio Books      4949.43
11170  2024-04-20                   TV and Video      9841.91

[11171 rows x 3 columns]

Date and Time Differences

In [32]:

%%sql

--Use INTERVALS

Select
  Interval '5 centuries'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

               interval
0  182500 days, 0:00:00

In [33]:
%%sql

SELECT
    CURRENT_DATE,
    orderdate
FROM Sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
    orderdate  >= Current_Date - Interval '5 years'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

115064 rows affected.

       current_date   orderdate
0        2025-08-21  2020-08-21
1        2025-08-21  2020-08-21
2        2025-08-21  2020-08-21
3        2025-08-21  2020-08-21
4        2025-08-21  2020-08-21
...             ...         ...
115059   2025-08-21  2024-04-20
115060   2025-08-21  2024-04-20
115061   2025-08-21  2024-04-20
115062   2025-08-21  2024-04-20
115063   2025-08-21  2024-04-20

[115064 rows x 2 columns]

In [34]:
%%sql

SELECT
    s.orderdate,
    p.categoryname,
    SUM(quantity * netprice * exchangerate) as net_revenue
FROM Sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
    s.orderdate >= Current_Date - Interval '5 years' -- last 5 years
GROUP BY s.orderdate, p.categoryname
Order BY s.orderdate, p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

9655 rows affected.

       orderdate                   categoryname  net_revenue
0     2020-08-21                          Audio       203.40
1     2020-08-21                    Cell phones      1600.48
2     2020-08-21                      Computers      1533.04
3     2020-08-21                 Games and Toys       391.71
4     2020-08-21                Home Appliances      4654.24
...          ...                            ...          ...
9650  2024-04-20                      Computers     58353.68
9651  2024-04-20                 Games and Toys      1744.30
9652  2024-04-20                Home Appliances      1562.04
9653  2024-04-20  Music, Movies and Audio Books      4949.43
9654  2024-04-20                   TV and Video      9841.91

[9655 rows x 3 columns]

In [35]:
%%sql

Select
  Extract(Day from Age('2024-01-14', '2024-01-08')) - 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  ?column?
0        1

In [36]:
%%sql
-- AGE() and EXTRACT ()
-- Average Processing Time

Select
  Date_part('year', orderdate) as order_year,
  Round(Avg(Extract(Day from Age(deliverydate, orderdate))), 2) as avg_processing_time,
  Cast(SUM(quantity * netprice * exchangerate) as integer) as net_revenue
FROM
  sales
Where orderdate >= Current_Date - Interval '5 years'
Group by order_year
Order by order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

   order_year avg_processing_time  net_revenue
0     2020.00                1.03      1740409
1     2021.00                1.36     21357977
2     2022.00                1.62     44864557
3     2023.00                1.75     33108566
4     2024.00                1.67      8396527

WINDOW FUNCTIONS

In [37]:
%%sql

Select
   customerkey,
   orderkey,
   linenumber,
   (quantity * netprice * exchangerate) AS net_revenue,
   AVG(quantity * netprice * exchangerate) OVER () as avg_net_revenue_all_orders,
   AVG(quantity * netprice * exchangerate) OVER (Partition By customerkey) as avg_net_revenue_this_customer
FROM sales
Order by customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderkey,linenumber,net_revenue,avg_net_revenue_all_orders,avg_net_revenue_this_customer
0,15,2259001,0,2217.41,1032.69,2217.41
1,180,1305016,0,525.31,1032.69,836.74
2,180,3162018,0,71.36,1032.69,836.74
3,180,3162018,1,1913.55,1032.69,836.74
4,185,1613010,0,1395.52,1032.69,1395.52
5,243,505008,0,287.67,1032.69,287.67
6,387,2495044,0,1265.56,1032.69,517.32
7,387,3242015,1,362.44,1032.69,517.32
8,387,3242015,0,30.51,1032.69,517.32
9,387,3242015,3,446.44,1032.69,517.32

In [38]:
%%sql

Select
   customerkey as customer,
   orderkey,
   linenumber,
   (quantity * netprice * exchangerate) AS net_revenue,
   AVG(quantity * netprice * exchangerate) OVER () as avg_net_revenue_all_orders,
   AVG(quantity * netprice * exchangerate) OVER (Partition By customerkey) as avg_net_revenue_this_customer
FROM sales
Order by customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customer,orderkey,linenumber,net_revenue,avg_net_revenue_all_orders,avg_net_revenue_this_customer
0,15,2259001,0,2217.41,1032.69,2217.41
1,180,1305016,0,525.31,1032.69,836.74
2,180,3162018,1,1913.55,1032.69,836.74
3,180,3162018,0,71.36,1032.69,836.74
4,185,1613010,0,1395.52,1032.69,1395.52
5,243,505008,0,287.67,1032.69,287.67
6,387,1451007,0,1608.10,1032.69,517.32
7,387,1451007,1,619.77,1032.69,517.32
8,387,1451007,2,97.05,1032.69,517.32
9,387,1451007,3,45.62,1032.69,517.32

In [42]:
%%sql

Select
   customerkey As customer,
   orderdate,
   (quantity * netprice * exchangerate) AS net_revenue,
   Row_Number() OVER (Partition By customerkey Order By quantity * netprice * exchangerate DESC) as order_rank,
   SUM(quantity * netprice * exchangerate) OVER (Partition By customerkey ORDER BY orderdate) as customer_running_total,
   SUM(quantity * netprice * exchangerate) OVER (Partition By customerkey) as customer_net_revenue,
   ((quantity * netprice * exchangerate) /  SUM(quantity * netprice * exchangerate) OVER (Partition By customerkey)) * 100 as pct_customer_revenue
FROM sales
Order by customerkey, orderdate
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customer,orderdate,net_revenue,order_rank,customer_running_total,customer_net_revenue,pct_customer_revenue
0,15,2021-03-08,2217.41,1,2217.41,2217.41,100.00
1,180,2018-07-28,525.31,2,525.31,2510.22,20.93
2,180,2023-08-28,1913.55,1,2510.22,2510.22,76.23
3,180,2023-08-28,71.36,3,2510.22,2510.22,2.84
4,185,2019-06-01,1395.52,1,1395.52,1395.52,100.00
5,243,2016-05-19,287.67,1,287.67,287.67,100.00
6,387,2018-12-21,619.77,3,2370.54,4655.84,13.31
7,387,2018-12-21,1608.10,1,2370.54,4655.84,34.54
8,387,2018-12-21,97.05,7,2370.54,4655.84,2.08
9,387,2018-12-21,45.62,8,2370.54,4655.84,0.98

In [53]:
%%sql

Select
  orderdate,
  orderkey * 10 + linenumber As order_line_number,
  (quantity* netprice * exchangerate) As net_revenue,
  Sum(quantity * netprice * exchangerate) Over(Partition by Orderdate) as daily_net_revenue,
  ((quantity * netprice * exchangerate) / Sum(quantity * netprice * exchangerate) Over(Partition by Orderdate)) * 100 as pct_daily_revenue
From sales
Limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10000,63.49,11640.80,0.55
1,2015-01-01,10001,423.28,11640.80,3.64
2,2015-01-01,10010,108.75,11640.80,0.93
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10021,950.25,11640.80,8.16
5,2015-01-01,10022,1302.91,11640.80,11.19
6,2015-01-01,10023,58.73,11640.80,0.50
7,2015-01-01,10030,224.98,11640.80,1.93
8,2015-01-01,10040,263.11,11640.80,2.26
9,2015-01-01,10041,578.52,11640.80,4.97